### ISSUE TITLE
ERROR: client version 1.22 is too old 

### ISSUE THREAD

**Issue by lienze87** [easychen/fangPHP#3]
我在window10 专业版（版本号：16299）尝试执行docker-compose up时发生以下错误：
>ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

在查阅资料后，在docker的官方Github的[Issues ERROR: client version 1.22 is too old #4106](https://github.com/docker/compose/issues/4106)中找到解决方案
>打开docker-compose.yaml文件，将 version:'2.0' 修改为 version:'2.1'

详细内容请打开链接自行查阅，希望对你有所帮助 ：)

**Comment by easychen** [comment]
感谢反馈，已更新。
