### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by ui-ui** [easychen/fangPHP#4]
<img width="444" alt="1" src="https://user-images.githubusercontent.com/18362721/35310279-992fb7ea-00eb-11e8-8c5f-83d6dc87cebb.png">

**Comment by easychen** [comment]
这个问题貌似是因为 docker compose 的 python 脚本 对中文用户目录的兼容性导致的，参考： http://blog.csdn.net/small_mouse0/article/details/54091135

因为没有测试环境，建议 ① 更换目录 ② 参考上文中的解决方案

因非本项目特有问题，此 issue 关闭。
