### ISSUE TITLE
mac环境启动docker报出 ERROR: unknown blob 错误

### ISSUE THREAD

**Issue by ghost** [easychen/fangPHP#7]
docker版本信息如下：

hanjundeMacBook-Pro:fangPHP hanjun$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

错误信息如下：
hanjundeMacBook-Pro:fangPHP hanjun$ docker-compose up
Pulling mysql.ftqq.com (hub.c.163.com/easychen/mysql-alpine:latest)...
latest: Pulling from easychen/mysql-alpine
75f2985e83e6: Pulling fs layer
75f2985e83e6: Downloading [>                                                  ] 75f2985e83e6: Downloading [==>                                                ] 75f2985e83e6: Downloading [======>                                            ]  257.5kB/2.065MBwnloading
75f2985e83e6: Downloading [=========>                                         ]  400.1kB/2.065MB
ffb020801b98: Downloading [==================================================>] ffb020801b98: Download complete

362e5191da4f: Downloading [==================================================>] 362e5191da4f: Download complete
ERROR: unknown blob

我所理解的blob错误通常都是资源配置错误，但fangPHP应该并没有引用静态资源。
或者 unknown blob 还有其它涵义？

**Comment by easychen** [comment]
我刚实测了一下，正常情况应该是可以运行的。感觉像是网络问题导致拉取的部分数据出现丢失，你重新pull试试。

我的环境：

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by ghost** [comment]
用最笨的方法下拉的zip压缩包然后解压运行，结果并没有什么区别。

**Comment by easychen** [comment]
@TieChi  嗯…… 难道是因为你开启了实验环境么？ Experimental: true  | Experimental: false


全部换成预编译好的镜像试试：

> 将 docker-composer.yaml 第4行  build: ./buildLNP 换成     image: hub.c.163.com/easychen/apncore:latest

**Comment by easychen** [comment]
@TieChi  另外我说的网络问题不是指 fangPHP 本身的代码，是说你电脑上的 docker 本地镜像，可以试试删掉重新拉取。

**Comment by ghost** [comment]
解决了。又一次被蓝灯坑了，关了之后重新下载docker镜像，就好了～～～
多谢～～～
吐血。。。
