### ISSUE TITLE
o.ftqq.com 改成我自己的应该修改那个文件呢？

### ISSUE THREAD

**Issue by Circleee** [easychen/fangPHP#9]
docker-compose.yaml 这个文件不对吧。

**Comment by easychen** [comment]
没错，docker-compose.yaml 里边的 o.ftqq.com 是容器host名称，只在composer组成的几个容器里边生效。

不明白的话，去看看 docker-compose 的手册。

**Comment by Circleee** [comment]
我还得看看  mysql 的密码改了也不生效。 ╮(╯▽╰)╭
